[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[features]
default = ["compile_shader","synth"]
compile_shader = []
record=[]
synth=["cpal","fluidlite","fluidlite-lib"]

[dependencies]
zerocopy = "0.3.0"
futures = "0.3.8"

# winit = "0.24.0"
winit = { git = "https://github.com/PolyMeilex/winit.git" } 

wgpu = "0.6.2"
wgpu_glyph = "0.10.0"


log = "0.4.11"
env_logger = "0.8.2"

nfd2 = "0.2.3"

lib_midi = {path="./lib_midi"}
midir = "0.7.0"

iced_native = "0.3.0"
iced_wgpu = {version="0.3.0", features=["image"]} 
iced_graphics = "0.1.0"

cpal = { version = "0.13.1", optional = true }
fluidlite = {git= "https://github.com/PolyMeilex/fluidlite-rs.git", optional = true}
fluidlite-lib = {git= "https://github.com/PolyMeilex/fluidlite-rs.git", optional = true}

# js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# web-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen" }
# console_error_panic_hook = "0.1.6"
# console_log = "0.2.0"

[build-dependencies]
glsl-to-spirv = "0.1.7"