[workspace]
members = [
    "piano-math",
    "wgpu-jumpstart",
    "neothesia",
    "neothesia-pipelines",
    "midi-file",
    "midi-io",
]

[workspace.dependencies]
wgpu = "0.16.1"
log = "0.4"
bytemuck = { version = "1.5", features = ["derive"] }
wgpu-jumpstart = { path = "./wgpu-jumpstart" }