[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[features]
default = ["compile_shader","record"]
compile_shader = []
record=["mpeg_encoder"]

[dependencies]
zerocopy = "0.3.0"
futures = "0.3.5"

winit = { version="0.22.2" }

wgpu = "0.5.2"
wgpu_glyph = "0.9.0"


log = "0.4"
env_logger = "0.7.1"

nfd2 = "0.2.1"

lib_midi = {path="./lib_midi"}
midir = "0.6.2"

# image = { version = "0.23.8", optional=true }
# ffmpeg-next = { version = "4.3.6", optional=true }
mpeg_encoder = {git="https://github.com/PolyMeilex/mpeg_encoder_next.git", features=["build"], optional=true}

# js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# web-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen" }
# console_error_panic_hook = "0.1.6"
# console_log = "0.2.0"

[build-dependencies]
glsl-to-spirv = "0.1"


# [patch.crates-io]
# wgpu = {git ="https://github.com/gfx-rs/wgpu-rs.git"}
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen" }
# web-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }