[package]
name = "neothesia"
version = "0.0.8"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"
default-run = "neothesia"

[features]
default = [ "app" ]

app = ["nfd2", "fluid-synth"]
record=["mpeg_encoder"]

play_along=[]

synth=[]
fluid-synth=["synth", "cpal", "fluidlite","fluidlite-lib"]
oxi-synth=["synth", "cpal", "oxisynth"]

[dependencies]
bytemuck = "1.5.0"
futures = "0.3.12"

# winit = "0.24.0"
winit = { git = "https://github.com/PolyMeilex/winit.git" } 

wgpu = "0.8.1"
wgpu_glyph = "0.12.0"


log = "0.4.14"
env_logger = "0.8.2"

nfd2 = { version="0.3.0", optional = true }

lib_midi = {path="./lib_midi"}
midir = "0.7.0"

iced_native = { git="https://github.com/hecrj/iced.git", rev="e292821c3780fc5a57c835815efc7a232ce4dc32" }
iced_wgpu = { git="https://github.com/hecrj/iced.git", rev="e292821c3780fc5a57c835815efc7a232ce4dc32", features = ["png"]} 
iced_graphics = { git="https://github.com/hecrj/iced.git", rev="e292821c3780fc5a57c835815efc7a232ce4dc32" } 

cpal = { version = "0.13.1", optional = true }
fluidlite = {git= "https://github.com/PolyMeilex/fluidlite-rs.git", optional = true}
fluidlite-lib = {git= "https://github.com/PolyMeilex/fluidlite-rs.git", optional = true}
oxisynth = {git= "https://github.com/PolyMeilex/OxiSynth.git", optional = true}

ron = "0.6.4"
serde = { version = "1.0.123", features = ["serde_derive"] }

mpeg_encoder = {git="https://github.com/PolyMeilex/mpeg_encoder_next.git", optional=true}
# mpeg_encoder = {path="../mpeg_encoder_next", optional=true}

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[[bin]]
name="neothesia-cli"
required-features = ["record"]

[[bin]]
name="neothesia"
required-features = ["app"]