[package]
name = "neothesia"
version = "0.0.16"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2021"
default-run = "neothesia"

[workspace]
members = [
    "lib-midi",
    "piano-math",
    "wgpu-jumpstart",
    "neothesia-pipelines",
    "midi-io",
]

[features]
default = ["app"]

app = [
    "rfd",
    "oxi-synth",
    "iced_native",
    "iced_wgpu",
    "iced_graphics",
    "iced_style",
    "play_along",
    "midi-io",
    "async-thread",
    "winit",
]
record = ["mpeg_encoder", "build-ffmpeg"]
# Download and compile ffmpeg
build-ffmpeg = ["mpeg_encoder/build"]

play_along = []

synth = []
fluid-synth = ["synth", "cpal", "fluidlite"]
oxi-synth = ["synth", "cpal", "oxisynth"]

[dependencies]
bytemuck = "1.5"
futures = "0.3"
log = "0.4"
env_logger = "0.10"
fps_ticker = "1.0"
ron = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
midi = "0.1"
num = "0.4"

wgpu = "0.14"
wgpu_glyph = "0.18"
wgpu-jumpstart = { path = "./wgpu-jumpstart" }

neothesia-pipelines = { path = "./neothesia-pipelines" }
lib-midi = { path = "./lib-midi" }
piano-math = { path = "./piano-math" }

# App Deps

winit = { version = "0.28.2", optional = true }
rfd = { version = "0.10", optional = true }
cpal = { version = "0.14", optional = true }
async-thread = { version = "0.1", optional = true }

fluidlite = { version = "0.2", features = ["builtin"], optional = true }
oxisynth = { version = "0.0.3", optional = true }

midi-io = { path = "./midi-io", optional = true }

iced_native = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", features = [
    "png",
    "image",
], optional = true }
iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }
iced_style = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }

# Recorder Deps

mpeg_encoder = { git = "https://github.com/PolyMeilex/mpeg_encoder_next.git", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[[bin]]
name = "neothesia-cli"
required-features = ["record"]

[[bin]]
name = "neothesia"
required-features = ["app"]
