[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2021"
default-run = "neothesia"

[features]
default = ["oxi-synth"]

synth = []
fluid-synth = ["synth", "cpal", "fluidlite"]
oxi-synth = ["synth", "cpal", "oxisynth"]

[dependencies]
futures = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
fps_ticker = "1.0"
ron = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
midi = "0.1"
num = "0.4"

wgpu = { workspace = true }
wgpu_glyph = "0.20.0"
wgpu-jumpstart = { workspace = true }

neothesia-core = { workspace = true }
neothesia-pipelines = { path = "../neothesia-pipelines" }
piano-math = { workspace = true }

# App Deps

winit = "0.28.2"
rfd = "0.11.2"
async-thread = "0.1"

cpal = { version = "0.15.0", optional = true }
fluidlite = { version = "0.2", features = ["builtin"], optional = true }
oxisynth = { version = "0.0.3", optional = true }

midi-file = { workspace = true }
midi-io = { path = "../midi-io" }

iced_style = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd" }
iced_graphics = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd" }
iced_core = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd" }
iced_runtime = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd" }
iced_wgpu = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd", features = [
    "image",
] }
iced_widget = { git = "https://github.com/PolyMeilex/iced.git", rev = "23af7ffc71693680455348fb350b2b66027adacd", features = [
    "image",
] }

[[bin]]
name = "neothesia"
